#  Esempio 04 s3 con notifica e lambda che fa una print su console
#  $ sam validate
#  $ sam build
#  $ sam deploy --stack-name esempio04s3notifica --capabilities CAPABILITY_IAM
#  opzionali: --parameter-overrides State=ENABLED BucketName=esempio04s3notificab
#  nota: --capabilities CAPABILITY_IAM è obbligatorio per le regole IAM
#  per provare caricamento con comando 
#  $ aws s3 cp prova.csv s3://esempio04s3notifica
#  $ sam logs --stack-name esempio04s3notifica
#  $ sam delete --stack-name esempio04s3notifica
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: > 
  Esempio 04 s3 con notifica e lambda che fa una print su console
Parameters:
  State:
    Type: String
    Default: ENABLED
    AllowedValues:
      - ENABLED
      - DISABLED
  BucketName:
    Type: String
    Description: Nome del bucket
    Default: esempio04s3notifica
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketName: !Ref BucketName
      MetricsConfigurations:
        - Id: EntireBucket
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: csv
            Function: !GetAtt S3Notification.Arn
    DeletionPolicy: Retain
  S3Notification:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        ZipFile: |
          import json
          def lambda_handler(event,context):
            for record in event['Records']:
              print("Esecuzione" + json.dumps(event) )
              bucket_name = record['s3']['bucket']['name']
              key_name = record['s3']['object']['key']
              print('Key found: ' + key_name + ' in Bucket: ' + bucket_name)
            return {'statusCode': 200 , 'body': 'OK'}
      Handler: index.lambda_handler
      Role: !GetAtt LambdaIAMRole.Arn
      Runtime: python3.6
      Timeout: 5
  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt S3Notification.Arn
      Action: 'lambda:InvokeFunction'
      Principal: s3.amazonaws.com
      SourceArn: !Join
      - ''
      - - 'arn:aws:s3:::'
        - !Ref BucketName
  LambdaIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetBucketNotification'
                  - 's3:PutBucketNotification'
                Resource: !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref BucketName
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'
Outputs:
  StackName:
    Description: Deployed StackName for update
    Value: !Ref AWS::StackName