AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS CloudFormation Examples by AlNao - 30 Sistema di gioco con WebSocket, REST API e logging

Parameters:
  StageName:
    Type: String
    Default: Prod
    Description: Nome dello stage API Gateway
  PlayersTableName:
    Type: String
    Default: esempio30-Players
    Description: Nome tabella giocatori
  MatchesTableName:
    Type: String
    Default: esempio30-Matches
    Description: Nome tabella match
  LogsTableName:
    Type: String
    Default: esempio30-Logs
    Description: Nome tabella log
  BansTableName:
    Type: String
    Default: esempio30-Bans
    Description: Nome tabella ban
  MaxInactivityDays:
    Type: Number
    Default: 42
    Description: Giorni massimi di inattività prima dell'eliminazione
  MaxNumberChangesPerDay:
    Type: Number
    Default: 5
    Description: Numero massimo di modifiche del numero per giorno
  FrontendBucketName:
    Type: String
    Default: esempio30-website-bucket
    Description: Nome del bucket S3 per il sito statico frontend

Globals:
  Function:
    Runtime: python3.11
    Timeout: 10
    MemorySize: 128
    Architectures: [arm64]

Resources:

  ### === IAM Roles === ###
  ApiGatewayCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      Tags:
        - Key: "StackName"
          Value: !Ref AWS::StackName
        - Key: "Project"
          Value: "Esempio30WebSocket"

  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchRole.Arn

  WebSocketLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Scan
                  - dynamodb:Query
                Resource:
                  - !GetAtt PlayersTable.Arn
                  - !GetAtt LogsTable.Arn
                  - !GetAtt MatchesTable.Arn
                  - !GetAtt BansTable.Arn
        - PolicyName: WebSocketManageConnections
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - execute-api:ManageConnections
                Resource: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocket}/*"
        - PolicyName: CloudWatchLogsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/apigateway/*"

  ### === DynamoDB Tables === ###
  PlayersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref PlayersTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: nickname
          AttributeType: S
      KeySchema:
        - AttributeName: nickname
          KeyType: HASH
      Tags:
        - Key: "StackName"
          Value: !Ref AWS::StackName
        - Key: "Project"
          Value: "Esempio30WebSocket"

  MatchesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref MatchesTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: matchId
          AttributeType: S
      KeySchema:
        - AttributeName: matchId
          KeyType: HASH
      Tags:
        - Key: "StackName"
          Value: !Ref AWS::StackName
        - Key: "Project"
          Value: "Esempio30WebSocket"

  LogsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref LogsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: timestamp
          KeyType: HASH
      Tags:
        - Key: "StackName"
          Value: !Ref AWS::StackName
        - Key: "Project"
          Value: "Esempio30WebSocket"

  BansTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref BansTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: nickname
          AttributeType: S
      KeySchema:
        - AttributeName: nickname
          KeyType: HASH
      Tags:
        - Key: "StackName"
          Value: !Ref AWS::StackName
        - Key: "Project"
          Value: "Esempio30WebSocket"

  ### === CloudWatch Logs === ###
  WebSocketApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/${WebSocket}"
      RetentionInDays: 14
      Tags:
        - Key: "StackName"
          Value: !Ref AWS::StackName
        - Key: "Project"
          Value: "Esempio30WebSocket"

  ### === WebSocket API === ###
  WebSocket:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub "${AWS::StackName}-websocket"
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"
      Tags:
        StackName: !Ref AWS::StackName
        Project: "Esempio30WebSocket"

  WebSocketConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocket
      RouteKey: $connect
      Target: !Sub integrations/${WebSocketConnectIntegration}

  WebSocketDisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocket
      RouteKey: $disconnect
      Target: !Sub integrations/${WebSocketDisconnectIntegration}

  # Route di default per messaggi senza action specifica (es. per nickname)
  WebSocketDefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocket
      RouteKey: $default
      Target: !Sub integrations/${WebSocketDefaultIntegration}

  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    DependsOn: 
      - WebSocketApiLogGroup
      - ApiGatewayAccount
    Properties:
      ApiId: !Ref WebSocket
      StageName: !Ref StageName
      AutoDeploy: true
      AccessLogSettings:
        DestinationArn: !GetAtt WebSocketApiLogGroup.Arn
        Format: '{"requestId":"$context.requestId","requestTime":"$context.requestTime","status":"$context.status","responseLength":"$context.responseLength","integrationLatency":"$context.integrationLatency","responseLatency":"$context.responseLatency","integrationStatus":"$context.integrationStatus","integrationError":"$context.integrationError","errorMessage":"$context.errorMessage","errorResponseType":"$context.errorResponseType","route":"$context.route","ip":"$context.identity.sourceIp","userAgent":"$context.identity.userAgent","connectionId":"$context.connectionId"}'
      DefaultRouteSettings:
        LoggingLevel: ERROR
        DataTraceEnabled: true
        DetailedMetricsEnabled: true
      Tags:
        StackName: !Ref AWS::StackName
        Project: "Esempio30WebSocket"

  ### === Lambda Functions (WebSocket) === ###
  WebSocketConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: connect.lambda_handler
      Role: !GetAtt WebSocketLambdaRole.Arn
      # Rimosso evento Api: la route WebSocket è gestita tramite Integration e Route
      Environment:
        Variables:
          PLAYERS_TABLE: !Ref PlayersTableName
          WS_ENDPOINT: !Sub "https://${WebSocket}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
      Tags:
        StackName: !Ref AWS::StackName
        Project: "Esempio30WebSocket"

  WebSocketDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: disconnect.lambda_handler
      Role: !GetAtt WebSocketLambdaRole.Arn
      # Rimosso evento Api: la route WebSocket è gestita tramite Integration e Route
      Environment:
        Variables:
          PLAYERS_TABLE: !Ref PlayersTableName
      Tags:
        StackName: !Ref AWS::StackName
        Project: "Esempio30WebSocket"

  SetNumberFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: set_number.lambda_handler
      Role: !GetAtt WebSocketLambdaRole.Arn
      Environment:
        Variables:
          PLAYERS_TABLE: !Ref PlayersTableName
          LOGS_TABLE: !Ref LogsTableName
          MAX_CHANGES_PER_DAY: !Ref MaxNumberChangesPerDay
      Tags:
        StackName: !Ref AWS::StackName
        Project: "Esempio30WebSocket"
      Events:
        SetNumber:
          Type: Api
          Properties:
            Path: /set-number
            Method: POST
            RestApiId: !Ref ServerlessRestApi
            Stage: !Ref StageName

  GuessNumberFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: guess_number.lambda_handler
      Role: !GetAtt WebSocketLambdaRole.Arn
      Environment:
        Variables:
          PLAYERS_TABLE: !Ref PlayersTableName
          MATCHES_TABLE: !Ref MatchesTableName
          LOGS_TABLE: !Ref LogsTableName
          BANS_TABLE: !Ref BansTableName
          WS_ENDPOINT: !Sub "https://${WebSocket}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
          MAX_CHANGES_PER_DAY: !Ref MaxNumberChangesPerDay
      Tags:
        StackName: !Ref AWS::StackName
        Project: "Esempio30WebSocket"
      Events:
        GuessNumber:
          Type: Api
          Properties:
            Path: /guess-number
            Method: POST
            RestApiId: !Ref ServerlessRestApi
            Stage: !Ref StageName


  ### === Lambda Functions (REST API) === ###
  GetScoresFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: get_scores.lambda_handler
      Environment:
        Variables:
          PLAYERS_TABLE: !Ref PlayersTableName
      Events:
        GetScores:
          Type: Api
          Properties:
            Path: /scores
            Method: GET
            RestApiId: !Ref ServerlessRestApi
            Stage: !Ref StageName
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PlayersTableName
        - AWSLambdaBasicExecutionRole
      Tags:
        StackName: !Ref AWS::StackName
        Project: "Esempio30WebSocket"

  BanUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: ban_user.lambda_handler
      Role: !GetAtt WebSocketLambdaRole.Arn
      Environment:
        Variables:
          BANS_TABLE: !Ref BansTableName
          LOGS_TABLE: !Ref LogsTableName
          PLAYERS_TABLE: !Ref PlayersTableName
          WS_ENDPOINT: !Sub "https://${WebSocket}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
      Events:
        BanUser:
          Type: Api
          Properties:
            Path: /admin/ban
            Method: POST
            RestApiId: !Ref ServerlessRestApi
            Stage: !Ref StageName
      Tags:
        StackName: !Ref AWS::StackName
        Project: "Esempio30WebSocket"

  GetMatchHistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: get_match_log.lambda_handler
      Events:
        GetMatches:
          Type: Api
          Properties:
            Path: /admin/matches
            Method: GET
            RestApiId: !Ref ServerlessRestApi
            Stage: !Ref StageName
      Environment:
        Variables:
          MATCHES_TABLE: !Ref MatchesTableName
          LOGS_TABLE: !Ref LogsTableName
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MatchesTableName
        - DynamoDBReadPolicy:
            TableName: !Ref LogsTableName
        - AWSLambdaBasicExecutionRole
      Tags:
        StackName: !Ref AWS::StackName
        Project: "Esempio30WebSocket"

  MatchControlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: match_control.lambda_handler
      Role: !GetAtt WebSocketLambdaRole.Arn
      Environment:
        Variables:
          PLAYERS_TABLE: !Ref PlayersTableName
          WS_ENDPOINT: !Sub "https://${WebSocket}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
      Events:
        Broadcast:
          Type: Api
          Properties:
            Path: /admin/broadcast
            Method: POST
            RestApiId: !Ref ServerlessRestApi
            Stage: !Ref StageName
        ResetNumbers:
          Type: Api
          Properties:
            Path: /admin/reset-numbers
            Method: POST
            RestApiId: !Ref ServerlessRestApi
            Stage: !Ref StageName
      Tags:
        StackName: !Ref AWS::StackName
        Project: "Esempio30WebSocket"

  ### === Lambda Permissions === ###
  WebSocketConnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WebSocketConnectFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocket}/*"

  WebSocketDisconnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WebSocketDisconnectFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocket}/*"

  # Permission per la route di default
  WebSocketDefaultPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WebSocketConnectFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocket}/*"

  ### === Integrations === ###
  WebSocketConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocket
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt WebSocketConnectFunction.Arn
      IntegrationMethod: POST
      PayloadFormatVersion: "1.0"
      #AWS::ApiGatewayV2::Integration per una Lambda, ma API Gateway WebSocket supporta solo la versione 1.0 per integrazioni Lambda.

  WebSocketDisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocket
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt WebSocketDisconnectFunction.Arn
      IntegrationMethod: POST
      PayloadFormatVersion: "1.0" 
      #AWS::ApiGatewayV2::Integration per una Lambda, ma API Gateway WebSocket supporta solo la versione 1.0 per integrazioni Lambda.

  # Integration di default che gestisce i messaggi generici (es. nickname)
  WebSocketDefaultIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocket
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt WebSocketConnectFunction.Arn
      IntegrationMethod: POST
      PayloadFormatVersion: "1.0"

  CorsOptionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: cors_options.lambda_handler
      Description: Risposta automatica alle richieste OPTIONS per CORS
      Policies:
        - AWSLambdaBasicExecutionRole
      Tags:
        StackName: !Ref AWS::StackName
        Project: "Esempio30WebSocket"
      Events:
        CorsOptionsRoot:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: OPTIONS
            RestApiId: !Ref ServerlessRestApi
            Stage: !Ref StageName

  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${AWS::StackName}-apirest"
      StageName: !Ref StageName
      Cors:
        # AllowCredentials: true # Unable to add Cors configuration because 'AllowCredentials' can not be true when 'AllowOrigin' is "'*'" or not set
        AllowMethods: "'POST, GET, DELETE, OPTIONS, PUT'"
        AllowOrigin: "'*'" #occhio che AllowOrigin va senza S finale https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-corsconfiguration.html
        AllowHeaders: "'*'"
        MaxAge: "'600'"
      Tags:
        - Key: "StackName"
          Value: !Ref AWS::StackName
        - Key: "Project"
          Value: !Sub "${AWS::StackName}ApiRest"

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref FrontendBucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
      MetricsConfigurations:
        - Id: EntireBucket
      Tags:
        - Key: "StackName"
          Value: !Ref AWS::StackName
        - Key: "Project"
          Value: "Esempio30WebSocket"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${FrontendBucket}/*"
            Condition:
              Bool:
                aws:SecureTransport: 'true'


  ### === Outputs === ###
Outputs:
  WebSocketURL:
    Description: URL della WebSocket API
    Value: !Sub "wss://${WebSocket}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
  RestApiEndpoint:
    Description: Endpoint REST API
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
  RestApiId:
    Description: "API Gateway Rest API ID"
    Value: !Ref ServerlessRestApi
  WebSocketApiId:
    Description: "API Gateway WebSocket API ID"
    Value: !Ref WebSocket
  ApiRegion:
    Description: "AWS Region"
    Value: !Ref AWS::Region
  FrontendBucketWebsiteURL:
    Description: URL pubblico del sito statico frontend
    Value: !GetAtt FrontendBucket.WebsiteURL
  WebSocketLogGroupName:
    Description: Nome del CloudWatch Log Group per WebSocket API
    Value: !Ref WebSocketApiLogGroup
