AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template con alcuni metodi di utilità per la gestione dei contenuti S3 (unzip, presigned url, ... )

Parameters:
  SourceBucket:
    Type: String
    Default: alberto-input
  SourcePathZip:
    Type: String
    Default: INPUT13/zip
  SourcePathFile:
    Type: String
    Default: INPUT13/file
  SourceUnzipFilePattern:
    Type: String
    Default: '*.zip'
  SourceExcelFilePattern:
    Type: String
    Default: '*.xlsx'
  DestCsvFile:
    Type: String
    Default: 'lista.csv'
  StateTrigger:
    Type: String
    Default: ENABLED
    AllowedValues:
      - ENABLED
      - DISABLED
  Stage:
    Type: String
    Default: dev
  LogTableName:
    Type: String
    Description: Nome del DB dynamo di Log
    Default: es13-logs-table
  DomainTableName: 
    Type: String
    Description: Nome del DB dynamo di Log
    Default: es13-domain-table

Resources:
  Unzzipper:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./unzip/template.yaml"
      Parameters:
        StateTrigger: !Ref StateTrigger
        SourceBucket: !Ref SourceBucket
        SourcePathZip: !Ref SourcePathZip
        DestBucket: !Ref SourceBucket
        DestPath: !Ref SourcePathFile
        SourceFilePattern: !Ref SourceUnzipFilePattern
  API:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./api/template.yaml"
      Parameters:
        SourceBucket: !Ref SourceBucket
        SourcePath: !Ref SourcePathFile
        Stage: !Ref Stage
  Uploader:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./uploader/template.yaml"
      Parameters:
        Stage: !Ref Stage
        BucketName: !Ref SourceBucket
        BucketPath: !Ref SourcePathZip
        DomainTableName: !Ref DomainTableName
        LogTableName: !Ref LogTableName
  Excel2csv:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./excel2csv/template.yaml"
      Parameters:
        StateTrigger: !Ref StateTrigger
        SourceBucket: !Ref SourceBucket
        SourcePathZip: !Ref SourcePathFile
        DestBucket: !Ref SourceBucket
        DestPath: !Ref SourcePathFile
        SourceFilePattern: !Ref SourceExcelFilePattern
        DestFileName: !Ref DestCsvFile
Outputs:
  StackName:
    Description: Deployed StackName for update
    Value: !Ref AWS::StackName
  EndpointAPI:
    Description: Endpoint URL API REST of Uploader
    Value: !GetAtt API.Outputs.Endpoint
  EndpointUploader:
    Description: Endpoint URL API REST of Uploader
    Value: !GetAtt Uploader.Outputs.Endpoint