AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template per caricamento CSV in RDS tramite S3 e AWS Glue

# Nota: questo template potrebbe prevedere dei costi aggiuntivi non trascurabili. Prestare attenzione prima di rilasciare questo template

Parameters:
  GlueName: 
    Type: String
    Default: es14-csv-to-rds-job
    Description: Nome del job glue
  BucketName:
    Type: String
    Default: formazione-sftp-simulator
    Description: Nome del bucket S3
  CSVPath:
    Type: String
    Default: INPUT/
    Description: Path nel bucket S3 per i file CSV
  RDSTableName:
    Type: String
    Default: persone
    Description: Nome della tabella RDS MySQL
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Choose which VPC the Application should be deployed to
  PrivateSubnet1:
    Description: Ec2SubnetId
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2:
    Description: Ec2SubnetId
    Type: AWS::EC2::Subnet::Id
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Resources:
#  S3Bucket:
#    Type: AWS::S3::Bucket
#    Properties:
#      BucketName: !Ref BucketName

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: mydb
      Engine: MySQL
      MasterUsername: admin
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref RDSSecret, ':SecretString:password}}' ]]
      DBInstanceClass: db.t3.micro
      AllocatedStorage: '20'
      PubliclyAccessible: false
      VPCSecurityGroups: 
        - !Ref SecurityGroup
      DBSubnetGroupName: !Ref SubnetGroup
      #BackupRetentionPeriod: 7
      #DeleteAutomatedBackups: false
      BackupRetentionPeriod: 0
      CopyTagsToSnapshot: false
      DeleteAutomatedBackups: true
      DeletionProtection: false
  SubnetGroup: #https://octopus.com/blog/creating-rds-instance-cloudformation
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupName: !Ref AWS::StackName
      DBSubnetGroupDescription: "Subnet Group"
      SubnetIds: # !GetAtt LAMPesVPC.Outputs.PrivateSubnets
      - !Ref PrivateSubnet1
      - !Ref PrivateSubnet2

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound access to RDS
      VpcId: !Ref VpcId
      SecurityGroupIngress:
#        - IpProtocol: tcp
#          FromPort: 3306
#          ToPort: 3306
#          SourceSecurityGroupId: !Ref SecurityGroup
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp
          FromPort: '0'
          ToPort: '65535' #no good and no best practice but glue use a port xxxx
          CidrIp: !Ref SSHLocation

  RDSSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: csv_to_rds_database
        Description: Database for CSV to RDS pipeline
  
  GlueTablePersone:
    Type: "AWS::Glue::Table"
    DependsOn: GlueDatabase
    Properties:
      TableInput: 
        TableType: "EXTERNAL_TABLE"
        Name: persone_csv
        Parameters: {
          "CrawlerSchemaDeserializerVersion": "1.0",
          "classification": "csv",
          "delimiter": ";",
          "skip.header.line.count": "1"
        }
        PartitionKeys: []
        StorageDescriptor:
          StoredAsSubDirectories: False
          InputFormat: "org.apache.hadoop.mapred.TextInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
          Columns:
            - Type: string
              Name: Nome
            - Type: string
              Name: Cognome
            - Type: string
              Name: Eta
          SerdeInfo:
            Parameters: {
            "field.delim": ";"
            }
            SerializationLibrary: "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
          Compressed: False
          Location: !Join ['', ['s3://', !Ref BucketName, '/' , !Ref CSVPath , persone.csv]]
        Retention: 0
      DatabaseName: !Ref GlueDatabase
      CatalogId: !Ref AWS::AccountId
  

  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: csv-s3-crawler
      Role: !Ref GlueRole
      DatabaseName: !Ref GlueDatabase
      Targets:
        S3Targets:
          - Path: !Sub s3://${BucketName}/${CSVPath}persone.csv
#      Schedule:
#        ScheduleExpression: cron(0 0 * * ? *)  # Run daily at midnight UTC
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"

  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Command: 
        Name: glueetl
        PythonVersion: "3"
        ScriptLocation: !Sub s3://${BucketName}/CODE/glue/glue_esempio14.py
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-enable"
        "--TempDir": !Sub s3://${BucketName}/temp/
        "--enable-metrics": ""
        "--enable-spark-ui": "true"
        "--spark-event-logs-path": !Sub s3://${BucketName}/sparkui/
        "--enable-job-insights": "true"
        "--enable-glue-datacatalog": ""
        "--database_name": !Ref GlueDatabase
        "--rds_connection_name": !Ref GlueRDSConnection
        "--rds_table_name": !Ref RDSTableName
      ExecutionProperty:
        MaxConcurrentRuns: 1
      GlueVersion: "3.0"
      MaxRetries: 0
      Name: !Ref GlueName #es14-csv-to-rds-job
      Role: !Ref GlueRole
      Connections:
        Connections: 
          - !Ref GlueRDSConnection

  GlueWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Name: Es14workflow
      Description: Workflow for processing CSV files and loading to RDS

  GlueStartTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: Es14glueTriggerCrawler
      Type: ON_DEMAND
      Description: Trigger to start the CSV processing workflow
      Actions:
        - CrawlerName: !Ref GlueCrawler
      WorkflowName: !Ref GlueWorkflow

  GlueJobTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: Es14glueTriggerRunJob
      Type: CONDITIONAL
      StartOnCreation: true #TRY
      Description: Trigger to run the Glue job after crawler completion
      WorkflowName: !Ref GlueWorkflow
      Actions:
        - JobName: !Ref GlueJob
      Predicate:
        Conditions:
          - LogicalOperator: EQUALS
            CrawlerName: !Ref GlueCrawler
            CrawlState: SUCCEEDED
#          - JobName: !Ref OnbAnagraficaFromAn01704
#            State: SUCCEEDED
#            LogicalOperator: EQUALS


  GlueRDSConnection:
    Type: AWS::Glue::Connection
    Properties:
      CatalogId: !Ref AWS::AccountId
      ConnectionInput:
        ConnectionType: JDBC
        ConnectionProperties:
          JDBC_CONNECTION_URL: !Sub 
            - jdbc:mysql://${RDSEndpoint}:3306/mydb
            - RDSEndpoint: !GetAtt RDSInstance.Endpoint.Address
          USERNAME: admin
          PASSWORD: !Join ['', ['{{resolve:secretsmanager:', !Ref RDSSecret, ':SecretString:password}}' ]]
        Name: rds-connection
        PhysicalConnectionRequirements:
          SecurityGroupIdList: 
            - !Ref SecurityGroup
          SubnetId: !Ref PrivateSubnet1

  GlueRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: GlueS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: 
                  - !Sub arn:aws:s3:::${BucketName}/*
        - PolicyName: GlueRDSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - rds-data:BatchExecuteStatement
                  - rds-data:BeginTransaction
                  - rds-data:CommitTransaction
                  - rds-data:ExecuteStatement
                  - rds-data:RollbackTransaction
                Resource: !Sub arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:${RDSInstance}
        - PolicyName: GlueSecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref RDSSecret

  GlueWorkerStarter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda
      Handler: start_workflow.entrypoint
      Runtime: python3.11
      MemorySize: 128
      Policies:
        - Statement:
          - Sid: AllowGlue
            Effect: Allow
            Action: 'glue:*'
            Resource: "*"

  CheckWorkFlowStatus:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda
      Handler: check_workflow_status.entrypoint
      Runtime: python3.11
      MemorySize: 128
      Policies:
        - Statement:
          - Sid: AllowGlue
            Effect: Allow
            Action: 'glue:*'
            Resource: "*"

  GlueWorkflowRunnerStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: STANDARD
      DefinitionUri: stepFunction/start_workflow.yaml
      Role: !GetAtt GlueWorkflowRunnerStateMachineRole.Arn
      Name: !Sub sf${AWS::StackName}
      DefinitionSubstitutions:
        StartWorkflowFnArn: !GetAtt GlueWorkerStarter.Arn
        CheckWorkFlowStatusFnArn: !GetAtt CheckWorkFlowStatus.Arn
        WorkflowName: !Ref GlueWorkflow #arn:aws:glue:${AWS::Region}:${AWS::AccountId}:workflow/${GlueWorkflow}
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt  StateMachinesLogGroup.Arn
        Level: ALL
        IncludeExecutionData: True

  GlueWorkflowRunnerStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: "glue-workflow-runner-stateMachine"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogDelivery'
                  - 'logs:GetLogDelivery'
                  - 'logs:UpdateLogDelivery'
                  - 'logs:DeleteLogDelivery'
                  - 'logs:ListLogDeliveries'
                  - 'logs:PutResourcePolicy'
                  - 'logs:DescribeResourcePolicies'
                  - 'logs:DescribeLogGroups'
                  - 'cloudwatch:PutMetricData'
                Resource: '*'
              - Effect: Allow
                Action: 
                  - 'lambda:InvokeFunction'
                Resource: 
                  - !GetAtt GlueWorkerStarter.Arn
                  - !GetAtt CheckWorkFlowStatus.Arn
              - Effect: Allow
                Action:
                  - 'events:PutEvents'
                Resource: '*'
             
  StateMachinesLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 3
      LogGroupName: !Join [ "", ["/aws/vendedlogs/states/", !Ref AWS::StackName, "-", "statemachine-logs"]]


  S3EventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - 'Object Created'
        detail:
          bucket:
            name:
              - !Ref BucketName
          object:
            key:
              - prefix: !Ref CSVPath
      State: ENABLED
      Targets:
        - Arn: !GetAtt GlueWorkflowRunnerStateMachine.Arn
          Id: !Sub sf${AWS::StackName}
          RoleArn: !GetAtt EventBridgeRole.Arn
#        - Arn: !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:workflow/${GlueWorkflow}
#          Id: "TriggerGlueWorkflow"
#          RoleArn: !GetAtt EventBridgeRole.Arn

  EventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GlueStartWorkflow
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'states:StartExecution'
                Resource: !GetAtt GlueWorkflowRunnerStateMachine.Arn
#              - Effect: Allow
#                Action:
#                  - glue:StartWorkflowRun
#                  - glue:NotifyEvent
#                Resource: !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:workflow/${GlueWorkflow}

Outputs:
  RDSEndpoint:
    Description: Endpoint RDS
    Value: !GetAtt RDSInstance.Endpoint.Address
  GlueJobName:
    Description: Nome del job Glue
    Value: !Ref GlueJob
  GlueCrawlerName:
    Description: Nome del Glue Crawler
    Value: !Ref GlueCrawler
  GlueDatabaseName:
    Description: Nome del Glue Database
    Value: !Ref GlueDatabase