AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Template CloudFormation - template che segue i passi: 
  - filtro per pattern
  - copia staging in
  - cancella originale
  - copia staging out 
  - invio a bucket applicativo

Parameters:
  SourceFilePattern:
    Type: String
    Description: Source Path solo il nome del file
    Default: prova*
  SourceBucket:
    Type: String
    Description: Source Bucket
    Default: alberto-input
  SourcePath:
    Type: String
    Description: Source Path senza barre iniziali e finali
    Default: INPUT
  StagingBucket:
    Type: String
    Description: Bucket destinazione
    Default: alberto-input2
  StagingFilePathIN:
    Type: String
    Description: Source Path solo il nome del file
    Default: INPUT
  StagingFilePathOUT:
    Type: String
    Description: Source Path senza barre iniziali e finali
    Default: OUTGOING
  DestBucket:
    Type: String
    Description: Bucket destinazione
    Default: bucket-invio
  DestFileName:
    Type: String
    Description: Source Path solo il nome del file
    Default: FILE_DESTINATION.txt
  DestPath:
    Type: String
    Description: Source Path senza barre iniziali e finali
    Default: folder

Resources:
  # TRIGGER ON S3 folder --> lambda --> application
  Esempio09Trigger:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./Trigger/trigger.yaml
      Parameters:
        SourceBucket: !Ref SourceBucket
        SourcePath: !Ref SourcePath
        StateMachineArn: !GetAtt Esempio09Application.Outputs.StateMachineArn
        StateMachineName: !GetAtt Esempio09Application.Outputs.StateMachineName
        SourceFilePattern: !Ref SourceFilePattern
  # application --> step function
  Esempio09Application:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./StateMachine/application.yaml
      Parameters:
        SFName: Esempio09StateMachine
        SourcePath: !Ref SourcePath
        SourceBucket: !Ref SourceBucket
        StagingBucket: !Ref StagingBucket
        StagingFilePathIN: !Ref StagingFilePathIN
        StagingFilePathOUT: !Ref StagingFilePathOUT
        DestBucket: !Ref DestBucket
        DestPath: !Ref DestPath
        DestFileName: !Ref DestFileName

Outputs:
  StackName:
    Description: Deployed StackName for update
    Value: !Ref AWS::StackName
...