AWSTemplateFormatVersion: 2010-09-09
Description: ECR e ECS using Cloudformation
# see aws examples from https://github.com/aws-samples/ecs-refarch-cloudformation/blob/master/master.yaml

Parameters:
  RepoName: 
    Description: Name for ecr repo 
    Type: String
    Default: formazione-ecs-repo-uno
  DesiredCount:
    Description: How many instances of this task should we run across our cluster?
    Type: Number
    Default: 2
  Path:
    Description: The path to register with the Application Load Balancer
    Type: String
    Default: /persone
  ImagePath:
    Description: The path in ECR
    Type: String
    Default: xxxx.dkr.ecr.eu-west-1.amazonaws.com/ecs-repo-uno
  ContainerName:
    Type: String
    Default: ecs-repo-uno
# old parameters if VPC availabile
#  VPC:
#    Description: The VPC that the ECS cluster is deployed to
#    Type: AWS::EC2::VPC::Id
#    Default: vpc-xxxxxx
#  Subnets:
#    Description: List of subnet 
#    Type: String
#    Default: subnet-xxxxxxxx,subnet-yyyyyyyyyy

Resources:
#  EcrRepo:
#    Type: AWS::ECR::Repository
#    Properties: 
#      RepositoryName: !Sub ${RepoName}-repo
#      ImageScanningConfiguration: 
#        ScanOnPush: true


  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ecs-refarch-cloudformation/infrastructure/vpc.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VpcCIDR: 10.180.0.0/16
        PublicSubnet1CIDR: 10.180.8.0/21
        PublicSubnet2CIDR: 10.180.16.0/21
        PrivateSubnet1CIDR: 10.180.24.0/21
        PrivateSubnet2CIDR: 10.180.32.0/21

  #examples from https://github.com/aws-samples/ecs-refarch-cloudformation/blob/master/master.yaml
  SecurityGroups: #security-groups.yaml
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ecs-refarch-cloudformation/infrastructure/security-groups.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !GetAtt VPC.Outputs.VPC #!Ref VPC
  ALB: #load-balancers.yaml
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ecs-refarch-cloudformation/infrastructure/load-balancers.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !GetAtt VPC.Outputs.VPC #!Ref VPC
        Subnets: !GetAtt VPC.Outputs.PublicSubnets #!Ref Subnets #important must be public
        SecurityGroup: !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup
  ECS: #ecs-cluster.yaml
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ecs-refarch-cloudformation/infrastructure/ecs-cluster.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        InstanceType: t2.micro
        ClusterSize: !Ref DesiredCount
        VPC: !GetAtt VPC.Outputs.VPC #!Ref VPC
        SecurityGroup: !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
        Subnets: !GetAtt VPC.Outputs.PrivateSubnets #!Ref Subnets #should be private
  # example https://s3.amazonaws.com/ecs-refarch-cloudformation/services/product-service/service.yaml
  EcsService:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      Cluster: !GetAtt ECS.Outputs.Cluster
      Role: !Ref ServiceRole
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: !Ref ContainerName # "persone-service"
          ContainerPort: 80
          TargetGroupArn: !Ref TargetGroup
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref ContainerName # persone-service
      ContainerDefinitions:
        - Name: !Ref ContainerName #  persone-service
          Essential: true
          Image: !Ref ImagePath
          Cpu: 256
          Memory: 512 #see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-cpu
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudWatchLogsGroup
              awslogs-region: !Ref AWS::Region
  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: 365
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !GetAtt VPC.Outputs.VPC #!Ref VPC
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /persone
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !GetAtt ALB.Outputs.Listener
      Priority: 2
      Conditions:
        - Field: path-pattern
          Values:
            - !Ref Path
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ecs-service-${AWS::StackName}
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "ecs.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      Policies:
        - PolicyName: !Sub ecs-service-${AWS::StackName}
          PolicyDocument:
            {
              "Version": "2012-10-17",
              "Statement":
                [
                  {
                    "Effect": "Allow",
                    "Action":
                      [
                        "ec2:AuthorizeSecurityGroupIngress",
                        "ec2:Describe*",
                        "elasticloadbalancing:DeregisterInstancesFromLoadBalancer",
                        "elasticloadbalancing:Describe*",
                        "elasticloadbalancing:RegisterInstancesWithLoadBalancer",
                        "elasticloadbalancing:DeregisterTargets",
                        "elasticloadbalancing:DescribeTargetGroups",
                        "elasticloadbalancing:DescribeTargetHealth",
                        "elasticloadbalancing:RegisterTargets",
                      ],
                    "Resource": "*",
                  },
                ],
            }
Outputs:
  ServiceUrl:
    Description: The URL endpoint for the website service
    Value: !Join ["", [!GetAtt ALB.Outputs.LoadBalancerUrl, "/"]]