AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template CloudFormation - Esempio14istanteEC2 - avvio ec2 da CloudFormation
Parameters:
  RegionAZ:
    Type: String
    Default: eu-west-1a
  VpcId:
    Type: String
    Default: vpc-0013c2751d04a7413
  EC2Ami:
    Type: String
    Default: ami-0b4b7dae3cafc3b88
Resources:
  ES14PubSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref RegionAZ
      CidrBlock: 10.199.84.0/24
      VpcId: !Ref VpcId
#  ES14IGW:
#    Type: AWS::EC2::InternetGateway
#    Properties:
#      Tags:
#        - Key: "Name"
#          Value: "ES14IGW"
  ES14IgwAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: 'igw-031fffc2b85e353fc' #!Ref ES14IGW
      VpcId: !Ref VpcId
  ES14NATa:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt ES14EIPa.AllocationId
      SubnetId: !Ref ES14PubSubnetA
      Tags:
        - Key: "Name"
          Value: "ES14NATa"
  ES14MainRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId
      Tags:
        - Key: "Name"
          Value: "MainRT"
  ES14MainRTRoute:
      Type: AWS::EC2::Route
      Properties:
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId: 'igw-031fffc2b85e353fc' #!Ref ES14IGW
        RouteTableId: !Ref ES14MainRT
  ES14EIPa:
    Type: AWS::EC2::EIP
    Properties:
      Tags:
        - Key: "Name"
          Value: "ES14EIPa"
  ES14MainRTSubnetAAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref ES14MainRT
      SubnetId: !Ref ES14PubSubnetA
  ES14ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Server security group'
      GroupName: 'ServerSecurityGroup'
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0'
          IpProtocol: TCP
          FromPort: 22
          ToPort: 22
        #- SourceSecurityGroupId: !Ref ES14LoadBalancerSecurityGroup
        - CidrIp: '0.0.0.0/0'
          IpProtocol: TCP
          FromPort: 8080
          ToPort: 8080
      SecurityGroupEgress:
        - CidrIp: '0.0.0.0/0' # Not for Prod
          IpProtocol: -1 # Allow all
      VpcId: !Ref VpcId
  ES14ServerAEC2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref RegionAZ
      KeyName: AlbertoNaoFormazione
      BlockDeviceMappings:
        - DeviceName: '/dev/sda1'
          Ebs:
            VolumeSize: 8 # in GB
      ImageId: !Ref EC2Ami
      InstanceType: 't2.micro' # t2.micro free tier
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          PrivateIpAddress: '10.199.84.4'
          SubnetId: !Ref ES14PubSubnetA
          DeviceIndex: '0'
          Description: 'Primary network interface'
          GroupSet:
            - !Ref ES14ServerSecurityGroup

          