AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Template CloudFormation - Esempio17lambdaUnzip 
  template esegue una lambda che verifica un token JWT

Parameters:
  SourceBucket:
    Type: String
    Default: alberto-input
  SourcePath:
    Type: String
    Default: INPUT
  SourceFilePattern:
    Type: String
    Default: PROVA.zip
  DestBucket:
    Type: String
    Default: alberto-input
  DestPath:
    Type: String
    Default: OUTPUT
  StateTrigger:
    Type: String
    Default: ENABLED
    AllowedValues:
      - ENABLED
      - DISABLED

Resources:
  Esempio17lambdaUnzipTriggerOnFilePutEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      State: !Ref StateTrigger
      EventPattern:
        source: 
          - "aws.s3"
        detail: 
          eventSource:
            - 's3.amazonaws.com'
          eventName:
            - 'CopyObject'
            - 'PutObject'
            - 'PutObjectAcl'
            - 'CompleteMultipartUpload'
          requestParameters:
            bucketName:
              - !Ref SourceBucket
            key:
              - prefix: !Ref SourcePath
      Targets:
        - Id: id1
          Arn: !GetAtt Esempio17lambdaUnzipLambda.Arn

  Esempio17lambdaUnzipPermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !GetAtt Esempio17lambdaUnzipLambda.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt Esempio17lambdaUnzipTriggerOnFilePutEventRule.Arn


  Esempio17lambdaUnzipLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda
      Handler: esempio17lambdaUnzip.entrypoint
      Runtime: python3.8
      MemorySize: 1280
      Timeout: 900
      Environment: 
        Variables:
          SourceBucket: !Ref SourceBucket
          SourcePath: !Ref SourcePath
          SourceFilePattern: !Ref SourceFilePattern
          DestBucket: !Ref DestBucket
          DestPath: !Ref DestPath
      Role: !GetAtt Esempio17lambdaUnzipLambdaIamRole.Arn

  Esempio17lambdaUnzipLambdaIamRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetBucketNotification'
                  - 's3:PutBucketNotification'
                Resource: !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref SourceBucket
              - Effect: Allow
                Action:
                  - 's3:GetObject'
#                  - 's3:PutObject'
                Resource: !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref SourceBucket
                  - '/*'
              - Effect: Allow
                Action:
#                  - 's3:GetObject'
                  - 's3:PutObject'
                Resource: !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref DestBucket
                  - '/*'
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'

Outputs:
  StackName:
    Description: Deployed StackName for update
    Value: !Ref AWS::StackName
...

