AWSTemplateFormatVersion: '2010-09-09'
Description: Esempio29 - AppSync GraphQL API "listaNote" con DynamoDB e interfaccia web

Parameters:
  ApiName:
    Type: String
    Default: esempio29-listaNote
    Description: Nome della GraphQL API
  TableName:
    Type: String
    Default: esempio29-listaNote
    Description: Nome della tabella DynamoDB

Resources:
  GraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Ref ApiName
      AuthenticationType: API_KEY
      Tags:
        - Key: Project
          Value: Esempio29GraphQL

  GraphQLSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      Definition: |
        type Nota {
          id: ID!
          testo: String!
        }
        type Query {
          getNote: [Nota]
        }
        type Mutation {
          addNota(testo: String!): Nota
          deleteNota(id: ID!): ID
        }
        schema {
          query: Query
          mutation: Mutation
        }
#      Tags:
#        - Key: Project
#          Value: Esempio29GraphQL

  GraphQLApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
# il valore è calcolato così:
# date -d "+7 days" +%s
      Expires: 1754760363 #non funziona: !Sub "{{resolve:timestamp: +7d}}"
#      Tags:
#        - Key: Project
#          Value: Esempio29GraphQL

  NoteTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: Esempio29GraphQL

  DataSourceDynamo:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      Name: NoteTableDataSource
      Type: AMAZON_DYNAMODB
      DynamoDBConfig:
        TableName: !Ref NoteTable
        AwsRegion: !Ref AWS::Region
      ServiceRoleArn: !GetAtt AppSyncDynamoRole.Arn
#      Tags:
#        - Key: Project
#          Value: Esempio29GraphQL

  AppSyncDynamoRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:Scan
                  - dynamodb:DeleteItem
                Resource: !GetAtt NoteTable.Arn
      Tags:
        - Key: Project
          Value: Esempio29GraphQL

  ResolverGetNote:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Query
      FieldName: getNote
      DataSourceName: !GetAtt DataSourceDynamo.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "Scan"
        }
      ResponseMappingTemplate: |
        $utils.toJson($ctx.result.items)

  ResolverAddNota:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Mutation
      FieldName: addNota
      DataSourceName: !GetAtt DataSourceDynamo.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "PutItem",
          "key": {
            "id": { "S": "$util.autoId()" }
          },
          "attributeValues": {
            "testo": { "S": "$ctx.args.testo" }
          }
        }
      ResponseMappingTemplate: |
        {
          "id": "$ctx.result.id.S",
          "testo": "$ctx.result.testo.S"
        }

  ResolverDeleteNota:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Mutation
      FieldName: deleteNota
      DataSourceName: !GetAtt DataSourceDynamo.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "DeleteItem",
          "key": {
            "id": { "S": "$ctx.args.id" }
          }
        }
      ResponseMappingTemplate: |
        "$ctx.args.id"

Outputs:
  GraphQLApiUrl:
    Description: URL dell'endpoint GraphQL
    Value: !GetAtt GraphQLApi.GraphQLUrl
  GraphQLApiKey:
    Description: API Key per l'accesso
    Value: !GetAtt GraphQLApiKey.ApiKey
  DynamoTableName:
    Description: Nome della tabella DynamoDB
    Value: !Ref NoteTable
  GraphQLApiId:
    Description: ID della GraphQL API
    Value: !GetAtt GraphQLApi.ApiId
  AwsRegion:
    Description: Regione AWS
    Value: !Ref AWS::Region
