AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Examples by AlNao - 03 BucketS3 con WebSite
# See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-policy.html'
# See https://repost.aws/knowledge-center/cloudformation-objectownership-acl-error

Parameters:
  NomeBucket:
    Type: String
    Default: esempio03buckets3
    Description: Nome del bucket
    MinLength: 9
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
#      AccessControl: PublicRead
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      BucketName: !Ref NomeBucket
      MetricsConfigurations:
        - Id: EntireBucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      Tags:
        - Key: "StackName"
          Value: !Ref AWS::StackName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      #https://repost.aws/knowledge-center/cloudformation-objectownership-acl-error
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
    #DeletionPolicy: Retain
  # AWS Foundational Security Best Practices v1.0.0 S3.5
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref NomeBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSSLRequestsOnly 
            Action: 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref NomeBucket
                - /*
            Principal: '*'
Outputs:
  WebsiteURL:
    Value: !GetAtt
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - S3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content
  StackName:
    Description: Deployed StackName for update
    Value: !Ref AWS::StackName