AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Esempio19efsEc2, template che crea una VPC (con eventualmente un relativo VPC endpoint) un EFS e una istanze Ec2 che monta il volume EFS

#SEE
# https://computingforgeeks.com/create-aws-efs-filesystem-with-cloudformation/
# https://github.com/1Strategy/efs-starter-template
# https://github.com/1Strategy/efs-starter-template/blob/master/efs.yaml

Parameters:
  CidrBlockVPC:
    Description: 'The IP address range to VPC'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.184.0.0/16
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x
#  CidrBlockVPCclient:
#    Description: 'The IP address range to VPC client'
#    Type: String
#    MinLength: '9'
#    MaxLength: '18'
#    Default: 10.185.0.0/16
#    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
#    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.
  DnsServers:
    Description: 'The IP address DNS into VPC'
    Type: String
    MinLength: '9'
    MaxLength: '15'
    Default: '10.184.0.2' #123.567.901.345
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})'
    ConstraintDescription: must be a valid IP of the form x.x.x.x
  CidrBlockSubnetA:
    Description: 'The IP address range to Subnet A'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.184.1.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  CidrBlockSubnetB:
    Description: 'The IP address range to Subnet B'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.184.2.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  CidrBlockSubnetC:
    Description: 'The IP address range to Subnet A'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.184.3.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  CidrBlockSubnetD:
    Description: 'The IP address range to Subnet B'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.184.4.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
#  ServerCertificateArn:
#    Description: The ARN of the server certificate. For more information, see the AWS Certificate Manager User Guide.
#    Type: String
#    Default: arn:aws:acm:eu-west-1:xxxxxxx:certificate/xxxxxxx
#  SAMLProviderArn:
#    Description: The Amazon Resource Name (ARN) of the IAM SAML identity provider.
#    Type: String
#    Default: arn:aws:iam::xxxxxxx:saml-provider/SAMLProvider
#  SelfServiceSAMLProviderArn:
#    Description: The Amazon Resource Name (ARN) of the IAM SAML identity provider for the self-service portal.
#    Type: String
#    Default: arn:aws:iam::xxxxxxx:saml-provider/SAMLprovider_self 
  SSHLocation:
    Description: ' The IP address range that can be used to SSH to the EC2 instances'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  RegionAZ:
    Type: String
    Default: eu-west-1a
  EC2Ami:
    Type: String
    Default: ami-015232c01a82b847b #ami-0b4b7dae3cafc3b88 #
  InstanceType:
    Type: String
    Default: 't2.micro'
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
  KeyName:
    Type: String
    Default: 'AlbertoNaoFormazione'

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ecs-refarch-cloudformation/infrastructure/vpc.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName #usato come tag per le risorse
        VpcCIDR: !Ref CidrBlockVPC # "10.84.0.0/16"
        PublicSubnet1CIDR: !Ref CidrBlockSubnetA # "10.84.1.0/24"
        PublicSubnet2CIDR: !Ref CidrBlockSubnetB # "10.84.2.0/24"
        PrivateSubnet1CIDR: !Ref CidrBlockSubnetC # "10.84.3.0/24"
        PrivateSubnet2CIDR: !Ref CidrBlockSubnetD # "10.84.4.0/24"
#  VPNendpoint:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: "../Esempio22vpnEndpoint/vpnendpoint.yaml"
#      Parameters:
#        VPCid: !GetAtt VPC.Outputs.VPC
#        SAMLProviderArn: !Ref SAMLProviderArn
#        SelfServiceSAMLProviderArn: !Ref SelfServiceSAMLProviderArn
#        CidrBlockVPC: !Ref CidrBlockVPC
#        CidrBlockVPCclient: !Ref CidrBlockVPCclient
#        ServerCertificateArn: !Ref ServerCertificateArn
#        SSHLocation: !Ref SSHLocation
#        DnsServers: !Ref DnsServers
#        PrivateSubnet1: !GetAtt VPC.Outputs.PrivateSubnet1
#        PrivateSubnet2: !GetAtt VPC.Outputs.PrivateSubnet2

  SecurityGroupGlobal:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !GetAtt VPC.Outputs.VPC
      GroupDescription: 'Web Server security group'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80' 
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation
      Tags:
        - Key: "Name"
          Value: !Ref AWS::StackName 
  EFS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./efs.yaml"
      Parameters:
        FileSystemName: !Ref AWS::StackName
        VpcId:  !GetAtt VPC.Outputs.VPC
        MountTarget1Subnet: !GetAtt VPC.Outputs.PublicSubnet1
        #MountTarget2Subnet: !GetAtt VPC.Outputs.PrivateSubnet1
        #MountTarget3Subnet: !GetAtt VPC.Outputs.PrivateSubnet2
        OriginSecurityGroup: !Ref SecurityGroupGlobal

  EC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./ec2elasticIp.yaml"
      Parameters:
        SecurityGroupGlobal: !Ref SecurityGroupGlobal
        RegionAZ: !Ref RegionAZ
        EC2Ami: !Ref EC2Ami
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SubnetId: !GetAtt VPC.Outputs.PublicSubnet1
        EFSFileSystemId: !GetAtt EFS.Outputs.FileSystemId

Outputs:
  StackName:
    Description: Deployed StackName for update
    Value: !Ref AWS::StackName
  EFSFileSystemId:
    Description: EFS name
    Value: !GetAtt EFS.Outputs.FileSystemId
  WebsiteURL:
    Description: Deployed StackName for update
    Value: !GetAtt EC2.Outputs.WebsiteURL
  InstanceIPAddress: #https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/services/EC2/EIP_With_Association.yaml
    Description: EC2 Instance IP Address
    Value: !GetAtt EC2.Outputs.InstanceIPAddress