AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template CloudFormation - Esempio19mappings - template con mappings
  
Mappings:
  EnvInstance:
    dev:
      EC2Type: t2.micro
    prod:
      EC2Type: t2.small

Parameters:
  EnvName:
    Type: String
    AllowedValues: [dev,prod]
    Default: dev
  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  VpcId:
    Type: String
    Default: vpc-0013c2751d04a7413
  RegionAZ:
    Type: String
    Default: eu-west-1a    
    
Resources:
  Esempio19mappingsinstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !FindInMap [EnvInstance, !Ref 'EnvName', EC2Type]
      ImageId: !Ref ImageId
      NetworkInterfaces:
      - GroupSet:
        - Ref: Esempio19mappingsSg
        SubnetId: 
          Ref: Esempio19mappingsPubSubnetA
        AssociatePublicIpAddress: true
        DeviceIndex: '0'
        DeleteOnTermination: true
  Esempio19mappingsSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
  Esempio19mappingsPubSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref RegionAZ # no !Ref "AWS::Region"
      CidrBlock: 10.199.84.0/24
      VpcId: !Ref VpcId
Outputs:
  StackName:
    Description: Deployed StackName for update
    Value: !Ref AWS::StackName
...

