AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template che crea un AGS, ALB (2x EC2) con apache/php e un RDS mysql
#SEE
# template ufficiali presi da https://github.com/aws-samples/ecs-refarch-cloudformation
# VPC: https://s3.amazonaws.com/ecs-refarch-cloudformation/infrastructure/vpc.yaml
# VPC: https://docs.aws.amazon.com/codebuild/latest/userguide/cloudformation-vpc-template.html
# SG: https://s3.amazonaws.com/ecs-refarch-cloudformation/infrastructure/security-groups.yaml
# ALB: https://s3.amazonaws.com/ecs-refarch-cloudformation/infrastructure/load-balancers.yaml

#See alsa:
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/sample-templates-appframeworks-us-west-2.html
# https://gist.github.com/christophchamp/56c99b000f19fb8c4552a336f5961dbe
# https://octopus.com/blog/creating-rds-instance-cloudformation
# https://stackoverflow.com/questions/61833725/value-of-property-vpczoneidentifier-must-be-of-type-list-of-string
#TODO https://computingforgeeks.com/configure-aws-application-load-balancer-with-cloudformation/

Parameters:
  CidrBlockVPC:
    Description: 'The IP address range to VPC'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.184.0.0/16
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x
  CidrBlockVPCclient:
    Description: 'The IP address range to VPC client'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.185.0.0/16
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.
  DnsServers:
    Description: 'The IP address DNS into VPC'
    Type: String
    MinLength: '9'
    MaxLength: '15'
    Default: '10.184.0.2' #123.567.901.345
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})'
    ConstraintDescription: must be a valid IP of the form x.x.x.x
  CidrBlockSubnetA:
    Description: 'The IP address range to Subnet A'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.184.1.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  CidrBlockSubnetB:
    Description: 'The IP address range to Subnet B'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.184.2.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  CidrBlockSubnetC:
    Description: 'The IP address range to Subnet A'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.184.3.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  CidrBlockSubnetD:
    Description: 'The IP address range to Subnet B'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.184.4.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  KeyName:
    Default: AlbertoNaoFormazione
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  DBName:
    Default: myDatabase
    Description: MySQL database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBUser:
    Default: alnao
    Description: Username for MySQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
  DBPassword:
    Default: bellissimo
    NoEcho: 'true'
    Description: Password for MySQL database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
  DBAllocatedStorage:
    Default: '5'
    Description: The size of the database (Gb)
    Type: Number
    MinValue: '5'
    MaxValue: '1024'
    ConstraintDescription: must be between 5 and 1024Gb.
  DBInstanceClass:
    Description: The database instance type
    Type: String
    Default: db.t2.small
    AllowedValues:
      - db.t1.micro
      - db.t2.micro
      - db.t2.small
    ConstraintDescription: must select a valid database instance type.
  MultiAZDatabase:
    Default: 'true'
    Description: Create a Multi-AZ MySQL Amazon RDS database instance
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    ConstraintDescription: must be either true or false.
  WebServerCapacity:
    Default: '1'
    Description: The initial number of WebServer instances
    Type: Number
    MinValue: '1'
    MaxValue: '5'
    ConstraintDescription: must be between 1 and 5 EC2 instances.
  WebServerCapacityMIN:
    Default: '1'
    Description: The initial number of WebServer instances
    Type: Number
    MinValue: '1'
    MaxValue: '5'
    ConstraintDescription: must be between 1 and 5 EC2 instances.
  WebServerCapacityMAX:
    Default: '2'
    Description: The initial number of WebServer instances
    Type: Number
    MinValue: '1'
    MaxValue: '5'
    ConstraintDescription: must be between 1 and 5 EC2 instances.
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.small
    AllowedValues:
      - t1.micro
      - t2.micro
      - t2.small
    ConstraintDescription: must be a valid EC2 instance type.
  SSHLocation:
    Description: ' The IP address range that can be used to SSH to the EC2 instances'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  ServerCertificateArn:
    Description: The ARN of the server certificate. For more information, see the AWS Certificate Manager User Guide.
    Type: String
    Default: arn:aws:acm:eu-west-1:<accountId>:certificate/ab033535-cee1-4cb8-a8e9-91336e966d63
  SAMLProviderArn:
    Description: The Amazon Resource Name (ARN) of the IAM SAML identity provider.
    Type: String
    Default: arn:aws:iam::<accountId>:saml-provider/SAMLProvider
  SelfServiceSAMLProviderArn:
    Description: The Amazon Resource Name (ARN) of the IAM SAML identity provider for the self-service portal.
    Type: String
    Default: arn:aws:iam::<accountId>:saml-provider/SAMLprovider_self 

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ecs-refarch-cloudformation/infrastructure/vpc.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName #usato come tag per le risorse
        VpcCIDR: !Ref CidrBlockVPC # "10.84.0.0/16"
        PublicSubnet1CIDR: !Ref CidrBlockSubnetA # "10.84.1.0/24"
        PublicSubnet2CIDR: !Ref CidrBlockSubnetB # "10.84.2.0/24"
        PrivateSubnet1CIDR: !Ref CidrBlockSubnetC # "10.84.3.0/24"
        PrivateSubnet2CIDR: !Ref CidrBlockSubnetD # "10.84.4.0/24"
  VPCendpoint:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./vpcendpoint.yaml"
      Parameters:
        VPCid: !GetAtt VPC.Outputs.VPC
        SAMLProviderArn: !Ref SAMLProviderArn
        SelfServiceSAMLProviderArn: !Ref SelfServiceSAMLProviderArn
        CidrBlockVPC: !Ref CidrBlockVPC
        CidrBlockVPCclient: !Ref CidrBlockVPCclient
        ServerCertificateArn: !Ref ServerCertificateArn
        SSHLocation: !Ref SSHLocation
        DnsServers: !Ref DnsServers
        PrivateSubnet1: !GetAtt VPC.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPC.Outputs.PrivateSubnet2
#  Ec2SingleWP:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: "./ec2singleWP.yaml"
#      Parameters:
#        VPCid: !GetAtt VPC.Outputs.VPC
#        KeyName: !Ref KeyName
#        SSHLocation: !Ref SSHLocation
#        DBName: !Ref DBName
#        DBUser: !Ref DBUser
#        DBPassword: !Ref DBPassword
#        DBRootPassword: !Ref DBPassword
# see https://github.com/getcft/aws-elb-to-ec2-target-group-cf-template/blob/master/elb-to-ec2-target-group-cf-template.yml

Outputs:
  StackName:
    Description: Deployed StackName for update
    Value: !Ref AWS::StackName
#    Value: !Join 
#      - ''
#      - - 'http://'
#        - !GetAtt 
#          - LAMPesALB
#          - DNSName
