apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: alnao/j-esempio02-backend-springboot:latest
          env:
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_HOST
              value: "aws-j-es03-cloudformation-eks-cluster-mysql.c9i2mk6uk701.eu-central-1.rds.amazonaws.com" # Sostituire con l'endpoint RDS dal CloudFormation
            - name: MYSQL_ROOT_PASSWORD
              value: "alnaoMeraviglioso"
            - name: CUSTOM_MESSAGE
              value: "Sono un messaggio custom dall'ambiente EKS AWS con CloudFormation Esempio27eks"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /api/persone/info
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/persone/info
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      dnsPolicy: "ClusterFirst"

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 80           # Porta del Service
      targetPort: 8080   # Porta del container


#---
# ConfigMap per configurazioni (opzionale)
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: springboot-config
#  namespace: default
#data:
#  application.properties: |
#    server.port=8080
#    spring.datasource.url=jdbc:mysql://SOSTITUISCI_CON_RDS_ENDPOINT:3306/nome_database
#    spring.datasource.username=root
#    spring.datasource.password=alnaoMeraviglioso
#    spring.jpa.hibernate.ddl-auto=update
#    spring.jpa.show-sql=true

---
# HorizontalPodAutoscaler per scaling automatico
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: springboot-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springboot-app
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80