AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Esempio di template CloudFormation per un processo che S3 -> Trigger -> Lambda -> Step Function -> Lambda

# Promemoria:
# Nel bucket sorgente deve essere attivata (manualmente) la proprietà EventBridgeConfiguration: EventBridgeEnabled: true

Parameters:
  SourceBucket:
    Type: String
    Description: Source Bucket
    Default: alberto-input
  SourcePath:
    Type: String
    Description: Source Path senza barre iniziali e finali
    Default: INPUT
  SourceFilePattern:
    Type: String
    Description: Source Path solo il nome del file
    Default: prova*
  DestBucket:
    Type: String
    Description: Bucket destinazione
    Default: alberto-input2
#  DestFileName:
#    Type: String
#    Description: Source Path solo il nome del file
#    Default: provaDest.csv
  DestFilePath:
    Type: String
    Description: Source Path senza barre iniziali e finali
    Default: OUTPUT

Resources:
  # TRIGGER --> lambda --> step function -> lambda
  Trigger:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./Trigger/template.yaml
      Parameters:
        SourceBucket: !Ref SourceBucket
        SourcePath: !Ref SourcePath
        StateMachineArn: !GetAtt StateMachine.Outputs.StateMachineArn
        StateMachineName: !GetAtt StateMachine.Outputs.StateMachineName
        SourceFilePattern: !Ref SourceFilePattern
  
  StateMachine:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./StateMachine/template.yaml
      Parameters:
        SFName: smEsempio08
        SourceBucket: !Ref SourceBucket
        SourcePath: !Ref SourcePath
        DestBucket: !Ref DestBucket
        #DestFileName: !Ref DestFileName
        DestFilePath: !Ref DestFilePath
        ProcessArn: !GetAtt Process.Outputs.ProcessArn
        
  Process:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./Process/template.yaml
      Parameters:
        DestBucket: !Ref DestBucket
        DestFilePath: !Ref DestFilePath
        #DestFileName: !Ref DestFileName
        #NO StateMachineArn: !GetAtt StateMachine.Outputs.StateMachineArn
        #NO StateMachineName: !GetAtt StateMachine.Outputs.StateMachineName

Outputs:
  StackName:
    Description: Deployed StackName for update
    Value: !Ref AWS::StackName
...