#Intestazione con la descrizione
AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Examples by AlNao - 01 BucketS3
# see documentation https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html

#blocco Parametri
Parameters:
  NomeBucket:
    Type: String
    Default: esempio01-bucket-s3
    Description: Nome del bucket
    MinLength: 9
#blocco Risorse
Resources:
  S3Bucket: #see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref NomeBucket
#blocco Outputs
Outputs:
  S3Bucket:
    Value: !GetAtt S3Bucket.Arn
    Description: S3 bucket ARN
  StackName:
    Description: Deployed StackName for update
    Value: !Ref AWS::StackName