AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template con conditions creazione di un volume a seconda di un parametro (dev/prod)

Mappings:
  EnvInstance:
    dev:
      EC2Type: t2.micro
    prod:
      EC2Type: t2.small

Parameters:
  EnvName:
    Type: String
    AllowedValues: [dev,prod]
    Default: dev
  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  VpcId:
    Type: String
    Default: vpc-0013c2751d04a7413
  RegionAZ:
    Type: String
    Default: eu-west-1a    

Conditions:
  CreateVolume: !Equals [!Ref EnvName, prod]
    
Resources:
  Es05Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !FindInMap [EnvInstance, !Ref 'EnvName', EC2Type]
      ImageId: !Ref ImageId
      NetworkInterfaces:
      - GroupSet:
        - Ref: Es05Sg
        SubnetId: 
          Ref: Es05PubSubnetA
        AssociatePublicIpAddress: false
        DeviceIndex: '0'
        DeleteOnTermination: true
      Tags:
        - Key: "Name"
          Value: !Ref AWS::StackName
  Es05VolumeAttachment:
    Type: AWS::EC2::VolumeAttachment
    Condition: CreateVolume
    Properties:
      InstanceId: !Ref Es05Instance
      VolumeId: !Ref Es05Volume
      Device: /dev/sdh
  Es05Volume:
    Type: AWS::EC2::Volume
    Condition: CreateVolume
    Properties:
      Size: 10
      AvailabilityZone: !Ref RegionAZ #!GetAtt Es05Instance.AvailabilityZone
  Es05Sg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
  Es05PubSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref RegionAZ # no !Ref "AWS::Region"
      CidrBlock: 10.199.83.0/24
      VpcId: !Ref VpcId
Outputs:
  StackName:
    Description: Deployed StackName for update
    Value: !Ref AWS::StackName
  VolumeId:
    Description: Volume ID if created
    Condition: CreateVolume
    Value: !Ref Es05Volume
...

