AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template CloudFormation - Esempio18parametriSSM - template con lettura parametri da SSM
  
Parameters:
  InstanceType:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /dev/ec2/instenceType
  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  VpcId:
    Type: String
    Default: vpc-0013c2751d04a7413
  RegionAZ:
    Type: String
    Default: eu-west-1a
    
Resources:
  Esempio18parametriSSMinstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      NetworkInterfaces:
      - GroupSet:
        - Ref: Esempio18parametriSSMSg
        SubnetId: 
          Ref: Esempio18parametriSSMPubSubnetA
        AssociatePublicIpAddress: true
        DeviceIndex: '0'
        DeleteOnTermination: true
  Esempio18parametriSSMSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
  Esempio18parametriSSMPubSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref RegionAZ
      CidrBlock: 10.199.84.0/24
      VpcId: !Ref VpcId
Outputs:
  StackName:
    Description: Deployed StackName for update
    Value: !Ref AWS::StackName
...

