AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: upload binary file from WebPage into S3

Parameters:
  Stage:
    Type: String
    Default: dev
  BucketName:
    Type: String
    Description: Bucket name
    Default: alberto-input
  BucketPath:
    Type: String
    Description: Bucket path
    Default: INPUT
  DomainTableName:
    Type: String
    Default: uploader-domain
  LogTableName:
    Type: String
    Description: Nome della tabella dynamo di log
    Default: uploader-log
  JwtKey:
    Type: String
    Default: AlbertoNaoBellissimo.123
Resources:
  #bucket
#  Bucket:
#    Type: 'AWS::S3::Bucket'
#    Properties:
#      BucketName: !Ref BucketName
#      OwnershipControls:
#        Rules:
#          - ObjectOwnership: ObjectWriter
#      VersioningConfiguration:
#        Status: Enabled
  #dynamo domain
  DynamoDomain:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DomainTableName
      AttributeDefinitions:
        - 
          AttributeName: "id"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
  #dynamo log
  LogUpload:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref LogTableName
      AttributeDefinitions:
        - 
          AttributeName: "id"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
  #lambda permission role
  APIRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: APIPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action:
                - "dynamodb:GetItem"
                - "dynamodb:Scan"
                Resource: !GetAtt DynamoDomain.Arn
              - Effect: Allow
                Action:
                - "dynamodb:PutItem"
                - "dynamodb:UpdateItem"
                - "dynamodb:DeleteItem"
                - "dynamodb:GetItem"
                - "dynamodb:Scan"
                Resource: !GetAtt LogUpload.Arn
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:PutObject'
                Resource: !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref BucketName
                  - '/*'
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:PutObject'
                Resource: !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref BucketName
              - Effect: Allow
                Action:
                  - 'sns:Publish'
                Resource: !Ref GenericSnsTopic
  #api gateway
  APIGateway:
    Type: AWS::Serverless::Api #https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html
    Properties:
      BinaryMediaTypes:
        - '*/*' # https://github.com/ParthTrambadiya/file-upload-sam/blob/master/template.yaml
      StageName: !Ref Stage
      OpenApiVersion: 3.0.2
      CacheClusterEnabled: false
      CacheClusterSize: '0.5'
      Cors:
        AllowMethods: "'POST, GET'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
      MethodSettings:
        - ResourcePath: /
          HttpMethod: GET
          CachingEnabled: false
          CacheTtlInSeconds: 300
        - ResourcePath: /
          HttpMethod: POST
          CachingEnabled: false
          CacheTtlInSeconds: 300
        - ResourcePath: / #https://stackoverflow.com/questions/59568148/enabling-binary-media-types-breaks-option-post-call-cors-in-aws-lambda
          HttpMethod: OPTIONS
          CachingEnabled: false
          CacheTtlInSeconds: 300
      Auth:
        DefaultAuthorizer: MyLambdaRequestAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          MyLambdaRequestAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: !GetAtt LambdaAuthorizer.Arn
            Identity:
              Headers:
                - Authorization
#        ResourcePolicy:
#          IpRangeWhitelist: #see https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-resourcepolicystatement.html
#            - "XX.XX.XX.XX" 
  GatewayResponseDefault4XX:
    Type: 'AWS::ApiGateway::GatewayResponse'
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
      ResponseType: DEFAULT_4XX
      RestApiId:
        Ref: APIGateway
  GatewayResponseDefault5XX:
    Type: 'AWS::ApiGateway::GatewayResponse'
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
      ResponseType: DEFAULT_5XX
      RestApiId:
        Ref: APIGateway

  #lambda function API
  GetFunction: 
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt APIRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: APIGateway
      Runtime: python3.11
      CodeUri: lambda
      Handler: list.handler
      MemorySize: 525
      Timeout: 600
      Environment: 
        Variables:
          DynamoName: !Ref LogTableName
  #see https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-resourcepolicystatement.html
  OptionsFunction: 
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt APIRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: options
            RestApiId:
              Ref: APIGateway
      Runtime: python3.11
      CodeUri: lambda
      Handler: list.handlerOptions
      MemorySize: 525
      Timeout: 600
      Environment: 
        Variables:
          DynamoName: !Ref LogTableName
  PostFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt APIRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
            RestApiId:
              Ref: APIGateway
      Runtime: python3.11
      CodeUri: lambda
      Handler: uploader.handler
      MemorySize: 525
      Timeout: 600
      Environment: 
        Variables:
          BucketName: !Ref BucketName
          BucketPath: !Ref BucketPath
          DomainTableName: !Ref DomainTableName
          LogTableName: !Ref LogTableName
          GenericSnsTopicArn: !Ref GenericSnsTopic

  LambdaAuthorizerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaAuthorizer
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${APIGateway}/*/*
  LambdaAuthorizer: 
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.11
      Role: !GetAtt APIRole.Arn
      CodeUri: lambda
      Handler: authJwt.entrypoint
      MemorySize: 512
      Timeout: 900
      Environment: 
        Variables:
          JwtKey: !Ref JwtKey
      Description: LambdaAuthorizer

  #SNS topic
  GenericSnsTopic:  #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: uploadGenericSns
      TopicName: uploadGenericSns

Outputs:
  StackName:
    Description: Deployed StackName for update
    Value: !Ref AWS::StackName
  Endpoint:
    Description: Endpoint URL API REST
    Value: !Sub https://${APIGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}
