AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Esempio topic SNS che invia i messaggi ad una coda SQS che invoca una lambda function

Parameters:
  EmailAddress:
    Type: String
    Description: Email address to subscribe to the SNS topic
    Default: alberto.nao@cherrybank.it

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "LambdaRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub "LambdaPolicy-sqs"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ReceiveMessage
                Resource: "*"
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'

  Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "es16queue"
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt QueueDLQ.Arn
        maxReceiveCount: 3

  QueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "es16dlq"
                
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "es16topic"

  SNSToQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "allow-sns-messages"
            Effect: Allow
            Principal: "*"
            Resource: !GetAtt Queue.Arn
            Action: "SQS:SendMessage"
            Condition:
              ArnEquals:
                "aws:SourceArn": !Ref SNSTopic
      Queues:
        - Ref: Queue

  QueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSTopic
      Endpoint: !GetAtt Queue.Arn
      Protocol: sqs
      RawMessageDelivery: "true"

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSTopic
      Protocol: email
      Endpoint: !Ref EmailAddress

  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda
      Handler: index.handler
      Runtime: python3.11
      MemorySize: 128
      Role: !Sub ${LambdaRole.Arn}
      Timeout: 30
      ReservedConcurrentExecutions: 5
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt Queue.Arn
            BatchSize: 1

  # IAM Role for Step Function
  StepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionSNSPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref SNSTopic

  # Step Function
  NotificationStepFunction:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt StepFunctionRole.Arn
      Name: 'sfEsempio16Sns'
      DefinitionString:
        !Sub
          - |-
            {
              "Comment": "A Step Function that sends a notification to SNS",
              "StartAt": "SendNotification",
              "States": {
                "SendNotification": {
                  "Type": "Task",
                  "Resource": "arn:aws:states:::sns:publish",
                  "Parameters": {
                    "TopicArn": "${SNSTopicArn}",
                    "Message.$": "$.message"
                  },
                  "End": true
                }
              }
            }
          - { SNSTopicArn: !Ref SNSTopic }
Outputs:
  SourceQueueURL:
    Description: "URL of source queue"
    Value: !Ref Queue
  SourceQueueARN:
    Description: "ARN of source queue"
    Value: !GetAtt Queue.Arn
  DeadLetterQueueURL:
    Description: "URL of dead-letter queue"
    Value: !Ref QueueDLQ
  DeadLetterQueueARN:
    Description: "ARN of dead-letter queue"
    Value: !GetAtt QueueDLQ.Arn
  StepFunctionArn:
    Description: ARN of the Step Function
    Value: !Ref NotificationStepFunction