AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ECR using Cloudformation
# see aws examples from https://github.com/aws-samples/ecs-refarch-cloudformation/blob/master/master.yaml

Parameters:
  RepoName: 
    Description: Name for ecr repo 
    Type: String
    Default: esempio23-ecr

Resources:
  EcrRepo:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Sub ${RepoName}-repository
      ImageScanningConfiguration: 
        ScanOnPush: true

Outputs:
  StackName:
    Description: Deployed StackName for update
    Value: !Ref AWS::StackName
  Arn:
    Value: !GetAtt EcrRepo.Arn
    Description: Repository Arn