# $ sam validate
# $ sam build
# $ sam deploy --stack-name esempio03parameters --capabilities CAPABILITY_IAM
# nota: --capabilities CAPABILITY_IAM è obbligatorio per le regole IAM
# $ aws s3 cp ../Esempio02bucketS3sito/index.html s3://esempio03parameters/
# $ sam delete --stack-name esempio03parameters
AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for s3 bucket con BucketPolicy
Parameters:
  State:
    Type: String
    Default: ENABLED
    AllowedValues:
      - ENABLED
      - DISABLED
  SourceBucket:
    Type: String
    Description: Nome del bucket
    Default: esempio03parameters
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      BucketName: !Ref SourceBucket
      MetricsConfigurations:
        - Id: EntireBucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SourceBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSSLRequestsOnly # AWS Foundational Security Best Practices v1.0.0 S3.5
            Action: 's3:GetObject'
            Effect: Allow
            Resource: !Join ["",["arn:aws:s3:::",!Ref SourceBucket,"/*"]]
            Principal: '*'
Outputs:
  WebsiteURL:
    Value: !GetAtt
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - S3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content